repos:
  - repo: local
    hooks:
      - id: run-tests
        name: Testes de integração
        entry: python -m unittest discover -s tests -p "*test*.py"
        language: system
        pass_filenames: false
        stages: [push]